# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo FengCheng"
license = "MIT"
licenselink = "https://github.com/xuyunan/hugo-fengcheng/blob/master/LICENSE"
description = ""
homepage = "https://github.com/xuyunan/hugo-fengcheng/"
tags = []
features = []
min_version = "0.65.0"

[author]
  name = "xuyunan"
  homepage = "https://xuyunan.github.io/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
